---
title: "baseline characteristics"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

#### Baseline characteristics starting the intervention

```{r}

# In this code chunk each of the 44 individual participant´s first test in the 
# in the intervention is found (based on the code list), and then mean baseline 
# characteristics of the participants are calculated

# Baseline characteristics when enrolled in the study (n = 44)

# Participants who´s first test was the pre test in CON
baseline_con <- pre_post_data %>%
  filter(period == "con", timepoint == "pre", 
         !id %in% c("18", "20", "40")) %>% # These id-s´first test was in MIT
  print()

# Participants who´s first test was the pre test in MIT
baseline_mit <- pre_post_data %>% 
  filter(period == "mit", timepoint == "pre", 
         !id %in% c("3", "8", "15", "16", "21", "36", "42")) %>% # These id-s´first test was in CON
  print()


baseline_intervention <- baseline_con %>%
  full_join(baseline_mit) %>% 
        summarise(age.m = mean(age, na.rm = TRUE),
                  age.s = sd(age, na.rm = TRUE),
                  
                  bodymass.m = mean(bodymass, na.rm = TRUE),
                  bodymass.s = sd(bodymass, na.rm = TRUE),
                  
                  bodyheight.m = mean(bodyheight, na.rm = TRUE),
                  bodyheight.s = sd(bodyheight, na.rm = TRUE),
                  
                  index.m = mean(index, na.rm = TRUE),
                  index.s = sd(index, na.rm = TRUE),
                  
                  w.rel.15tt.m = mean(w.rel.15tt, na.rm = TRUE),
                  w.rel.15tt.s = sd(w.rel.15tt, na.rm = TRUE),
                  
                  w.rel.max.m = mean(w.rel.max, na.rm = TRUE),
                  w.rel.max.s = sd(w.rel.max, na.rm = TRUE),
                  
                  w.rel.4mmol.m = mean(w.rel.4mmol, na.rm = TRUE),
                  w.rel.4mmol.s = sd(w.rel.4mmol, na.rm = TRUE),

                  vo2.rel.max.m = mean(vo2.rel.max, na.rm = TRUE),
                  vo2.rel.max.s = sd(vo2.rel.max, na.rm = TRUE),
                  
                  p.vo2.4mmol.m = mean(p.vo2.4mmol, na.rm = TRUE),
                  p.vo2.4mmol.s = sd(p.vo2.4mmol, na.rm = TRUE),
                  
                  ge.3.fresh.m = mean(ge.3.fresh, na.rm = TRUE),
                  ge.3.fresh.s = sd(ge.3.fresh, na.rm = TRUE),
                  
                  ge.3.tired.m = mean(ge.3.tired, na.rm = TRUE),
                  ge.3.tired.s = sd(ge.3.tired, na.rm = TRUE)) %>% 
        
        # Changing the names of the variables and choosing decimals 
        mutate("Age (years)" = paste0(round(age.m, 1), " (", round(age.s, 1),")"),
               "Body mass (kg)" = paste0(round(bodymass.m, 1), " (", round(bodymass.s, 1),")"),
               "Body height (cm)" = paste0(round(bodyheight.m, 1), " (", round(bodyheight.s, 1),")"),
               "Index (W/kg)" = paste0(round(index.m, 3), " (", round(index.s, 3),")"),
               "PO 15min (W/kg)" = paste0(round(w.rel.15tt.m, 2), " (", round(w.rel.15tt.s, 2),")"),
               "PO VO2max (W/kg)" = paste0(round(w.rel.max.m, 2), " (", round(w.rel.max.s, 2),")"),
               "PO 4mmol/L La- (W/kg)" = paste0(round(w.rel.4mmol.m, 2), " (", round(w.rel.4mmol.s, 2),")"),
               "VO2max (ml/kg/min)" = paste0(round(vo2.rel.max.m, 1), " (", round(vo2.rel.max.s, 1),")"),
               "% VO2maks 4mmol/L La- (%)" = paste0(round(p.vo2.4mmol.m, 1), " (", round(p.vo2.4mmol.s, 1),")"),
               "GE 3. last bout fresh (%)" = paste0(round(ge.3.fresh.m, 1), " (", round(ge.3.fresh.s, 1),")")) %>% 
  
  
        # Choosing which variables to put in the table
        select("Age (years)":"GE 3. last bout fresh (%)") %>%
  
        # Making the table prettier
        pivot_longer(names_to = "variable", values_to = "stat", "Age (years)":"GE 3. last bout fresh (%)") %>%
        pivot_wider(names_from = variable, values_from = stat) %>%
  view()



# Calculating baseline characteristics at onset of each training period (n = 44)

baseline <- pre_post_data %>%
  filter(timepoint == "pre") %>% 
  group_by(period) %>% 
        summarise(age.m = mean(age, na.rm = TRUE),
                  age.s = sd(age, na.rm = TRUE),
                  
                  bodymass.m = mean(bodymass, na.rm = TRUE),
                  bodymass.s = sd(bodymass, na.rm = TRUE),
                  
                  bodyheight.m = mean(bodyheight, na.rm = TRUE),
                  bodyheight.s = sd(bodyheight, na.rm = TRUE),
                  
                  index.m = mean(index, na.rm = TRUE),
                  index.s = sd(index, na.rm = TRUE),
                  
                  w.rel.15tt.m = mean(w.rel.15tt, na.rm = TRUE),
                  w.rel.15tt.s = sd(w.rel.15tt, na.rm = TRUE),
                  
                  w.rel.max.m = mean(w.rel.max, na.rm = TRUE),
                  w.rel.max.s = sd(w.rel.max, na.rm = TRUE),
                  
                  w.rel.4mmol.m = mean(w.rel.4mmol, na.rm = TRUE),
                  w.rel.4mmol.s = sd(w.rel.4mmol, na.rm = TRUE),

                  vo2.rel.max.m = mean(vo2.rel.max, na.rm = TRUE),
                  vo2.rel.max.s = sd(vo2.rel.max, na.rm = TRUE),
                  
                  p.vo2.4mmol.m = mean(p.vo2.4mmol, na.rm = TRUE),
                  p.vo2.4mmol.s = sd(p.vo2.4mmol, na.rm = TRUE),
                  
                  ge.3.fresh.m = mean(ge.3.fresh, na.rm = TRUE),
                  ge.3.fresh.s = sd(ge.3.fresh, na.rm = TRUE),
                  
                  ge.3.tired.m = mean(ge.3.tired, na.rm = TRUE),
                  ge.3.tired.s = sd(ge.3.tired, na.rm = TRUE)) %>% 
        
        # Changing the names of the variables and choosing decimals 
        mutate("Age (years)" = paste0(round(age.m, 1), " (", round(age.s, 1),")"),
               "Body mass (kg)" = paste0(round(bodymass.m, 1), " (", round(bodymass.s, 1),")"),
               "Body height (cm)" = paste0(round(bodyheight.m, 1), " (", round(bodyheight.s, 1),")"),
               "Index (W/kg)" = paste0(round(index.m, 3), " (", round(index.s, 3),")"),
               "PO 15min (W/kg)" = paste0(round(w.rel.15tt.m, 2), " (", round(w.rel.15tt.s, 2),")"),
               "PO VO2max (W/kg)" = paste0(round(w.rel.max.m, 2), " (", round(w.rel.max.s, 2),")"),
               "PO 4mmol/L La- (W/kg)" = paste0(round(w.rel.4mmol.m, 2), " (", round(w.rel.4mmol.s, 2),")"),
               "VO2max (ml/kg/min)" = paste0(round(vo2.rel.max.m, 1), " (", round(vo2.rel.max.s, 1),")"),
               "% VO2maks 4mmol/L La- (%)" = paste0(round(p.vo2.4mmol.m, 1), " (", round(p.vo2.4mmol.s, 1),")"),
               "GE 3. last bout fresh (%)" = paste0(round(ge.3.fresh.m, 1), " (", round(ge.3.fresh.s, 1),")")) %>% 
  
  
        # Choosing which variables to put in the table
        select(period, "Age (years)":"GE 3. last bout fresh (%)") %>%
  
        # Making the table prettier
        pivot_longer(names_to = "variable", values_to = "stat", "Age (years)":"GE 3. last bout fresh (%)") %>%
        pivot_wider(names_from = period, values_from = stat) %>%
  view()


write_xlsx(baseline, "C:\\ir-mit-hit\\baseline_ir.xlsx")




```

#### Training history

```{r}

# In this code chunk the participants average training history before the 
# intervention is calculated


training_history <-read_excel("data/training_history_ir_data.xlsx", na = "na") %>% 
       summarise(active.years.m = mean(active.years, na.rm = TRUE),
                  active.years.s = sd(active.years, na.rm = TRUE)) %>% print()


```

#### Temperature at all prolonged cycling tests

```{r}

# In this code chunk the ambient temperature at all prolonged cycling tests
# is calculated

temp.tests <-
  cycling_data %>%
  select(id, temperature.start) %>% 
  summarise(temp.m = mean(temperature.start, na.rm = TRUE),
            temp.s = sd(temperature.start, na.rm = TRUE)) %>% 
  print()

```


