---
title: "relationship ir mit hit"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

#### Relationship between individual observed responses to MIT and HIT 

```{r}

# In this code chunk simple linear models are made to investigate whether there
# is a relationship between the observed individual responses/outcomes/changes
# for the 22 participants in the MIT block and the HIT block for all 
# investigated outcome variables. More over, ICC scores are computed to 
# investigate the reliability of the changes in outcome variables between blocks


## Performance index

# Formatting data to fit analyses
relation_data <- data %>%
  filter(period != "con") %>% 
  filter(variable == "index") %>% 
  select(id, period, change) %>% 
  pivot_wider(names_from = period,
              values_from = change) %>% 
  subset(select = -id) %>%
  print()

pearsons.r <- cor.test(relation_data$mit, relation_data$hit, method = "pearson") %>% print()
mod <- lm(mit ~ hit, data = relation_data) 
summ(mod, confint = TRUE, digits = 3)

# ICC score
icc <- ICC(relation_data, alpha=.05, missing = TRUE) %>%  print()

# Printing linear model
fig <- ggplot(relation_data, aes(x=hit, y=mit)) +
  geom_point() +
  geom_smooth(method="lm", colour = "black") +
  theme_pubr() +
  scale_y_continuous(breaks=seq(-0.01, 0.12, 0.02)) + 
  scale_x_continuous(breaks=seq(-0.01, 0.06, 0.02)) + 
  labs(x = "HIT ∆ performance index (AU)", 
       y = "MIT ∆ performance index (AU)") +
  theme(text=element_text(family="serif", face="plain", size=11))
fig


## PO15min

relation_data <- data %>%
  filter(period != "con") %>% 
  filter(variable == "w.rel.15tt") %>% 
  select(id, period, change) %>% 
  pivot_wider(names_from = period,
              values_from = change) %>% 
  subset(select = -id) %>%
  print()

pearsons.r <- cor.test(relation_data$mit, relation_data$hit, method = "pearson") %>% print()
mod <- lm(mit ~ hit, data = relation_data) 
summ(mod, confint = TRUE, digits = 3)

icc <- ICC(relation_data, alpha=.05, missing = TRUE) %>%  print()

mit_hit_fig <- ggplot(relation_data, aes(x=mit, y=hit)) +
  geom_point() +
  geom_smooth(method="lm", colour = "black") +
  theme_pubr() +
  labs(x = expression("MIT   ∆ PO"["15-min"]*"  ( W ∙ kg"^-1*") "), 
       y = expression("HIT   ∆ PO"["15-min"]*"  ( W ∙ kg"^-1*") ")) +
  theme(text=element_text(family="serif", face="plain", size=11))
mit_hit_fig

saveRDS(SDir.fig, "./figures/rds/mit_hit_fig.RDS")


ggsave("figures/mit_hit_fig.pdf", plot = mit_hit_fig, width = 25, height = 20,
       dpi = 600,
       units = "cm",
       device = cairo_pdf)



## pVO2max

relation_data <- data %>%
  filter(period != "con") %>% 
  filter(variable == "w.rel.max") %>% 
  select(id, period, change) %>% 
  pivot_wider(names_from = period,
              values_from = change) %>% 
  subset(select = -id) %>%
  print()

pearsons.r <- cor.test(relation_data$mit, relation_data$hit, method = "pearson") %>% print()
mod <- lm(mit ~ hit, data = relation_data) 
summ(mod, confint = TRUE, digits = 3)

icc <- ICC(relation_data, alpha=.05, missing = TRUE) %>%  print()

fig <- ggplot(relation_data, aes(x=hit, y=mit)) +
  geom_point() +
  geom_smooth(method="lm", colour = "black") +
  theme_pubr() +
  labs(x = expression("HIT   ∆ pVO"["2max"]*"  ( W ∙ kg"^-1*") "), 
       y = expression("MIT   ∆ pVO"["2max"]*"  ( W ∙ kg"^-1*") ")) +
  theme(text=element_text(family="serif", face="plain", size=11))
fig


## PO4mmol

relation_data <- data %>%
  filter(period != "con") %>% 
  filter(variable == "w.rel.4mmol") %>% 
  select(id, period, change) %>% 
  pivot_wider(names_from = period,
              values_from = change) %>% 
  subset(select = -id) %>%
  print()

pearsons.r <- cor.test(relation_data$mit, relation_data$hit, method = "pearson") %>% print()
mod <- lm(mit ~ hit, data = relation_data) 
summ(mod, confint = TRUE, digits = 3)

icc <- ICC(relation_data, alpha=.05, missing = TRUE) %>%  print()

fig <- ggplot(relation_data, aes(x=hit, y=mit)) +
  geom_point() +
  geom_smooth(method="lm", colour = "black") +
  theme_pubr() +
  labs(x = expression("HIT   ∆ PO"["4mmol"]*"  ( W ∙ kg"^-1*") "), 
       y = expression("MIT   ∆ PO"["4mmol"]*"  ( W ∙ kg"^-1*") ")) +
  theme(text=element_text(family="serif", face="plain", size=11))
fig


## VO2max

relation_data <- data %>%
  filter(period != "con") %>% 
  filter(variable == "vo2.rel.max") %>% 
  select(id, period, change) %>% 
  pivot_wider(names_from = period,
              values_from = change) %>% 
  subset(select = -id) %>%
  print()

pearsons.r <- cor.test(relation_data$mit, relation_data$hit, method = "pearson") %>% print()
mod <- lm(mit ~ hit, data = relation_data) 
summ(mod, confint = TRUE, digits = 3)

icc <- ICC(relation_data, alpha=.05, missing = TRUE) %>%  print()

fig <- ggplot(relation_data, aes(x=hit, y=mit)) +
  geom_point() +
  geom_smooth(method="lm", colour = "black") +
  theme_pubr() +
  labs(x = expression("HIT   ∆ VO"["2max"]*"  ( mL ∙ min"^-1*" ∙ kg"^-1*") "), 
       y = expression("MIT   ∆ VO"["2max"]*"  ( mL ∙ min"^-1*" ∙ kg"^-1*") ")) +
  theme(text=element_text(family="serif", face="plain", size=11))
fig


## % of VO2max at 4mmol [LA-]

relation_data <- data %>%
  filter(period != "con") %>% 
  filter(variable == "p.vo2.4mmol") %>% 
  select(id, period, change) %>% 
  pivot_wider(names_from = period,
              values_from = change) %>% 
  subset(select = -id) %>%
  print()

pearsons.r <- cor.test(relation_data$mit, relation_data$hit, method = "pearson") %>% print()
mod <- lm(mit ~ hit, data = relation_data) 
summ(mod, confint = TRUE, digits = 3)

icc <- ICC(relation_data, alpha=.05, missing = TRUE) %>%  print()

fig <- ggplot(relation_data, aes(x=hit, y=mit)) +
  geom_point() +
  geom_smooth(method="lm", colour = "black") +
  theme_pubr() +
  labs(x = expression("HIT   ∆ % of VO"["2max"]*"  ( %-points) "), 
       y = expression("MIT   ∆ % of VO"["2max"]*"  ( %-points) ")) +
  theme(text=element_text(family="serif", face="plain", size=11))
fig


## GE (at the 3.last bout of the blood lactate profile in the fresh state)

relation_data <- data %>%
  filter(period != "con") %>% 
  filter(variable == "ge.3.fresh") %>% 
  select(id, period, change) %>% 
  pivot_wider(names_from = period,
              values_from = change) %>% 
  subset(select = -id) %>%
  print()

pearsons.r <- cor.test(relation_data$mit, relation_data$hit, method = "pearson") %>% print()
mod <- lm(mit ~ hit, data = relation_data) 
summ(mod, confint = TRUE, digits = 3)

icc <- ICC(relation_data, alpha=.05, missing = TRUE) %>%  print()

fig <- ggplot(relation_data, aes(x=hit, y=mit)) +
  geom_point() +
  geom_smooth(method="lm", colour = "black") +
  theme_pubr() +
  labs(x = "HIT   ∆ GE (%-points)", 
       y = "MIT   ∆ GE (%-points)") +
  theme(text=element_text(family="serif", face="plain", size=11))
fig

```


```{r}

# Figure 4

axis.width <- 0.2
axis.ticks.width <- 0.2
lable.size <- 5
line.width <- 0.3
point.size <- 0.4



figure4 <- ggplot(relation_data, aes(x=mit, y=hit)) +
  geom_point(size = point.size, colour = "grey") +
  geom_smooth(method="lm", se=TRUE, level = 0.95, lwd = line.width, colour = "black") +
  theme_pubr() +
  scale_y_continuous(limits = c(-0.02, 0.06), 
                     breaks = seq(from = -0.02, to = 0.06, by = 0.02), 
                     expand = c(0.005, 0.005)) +
  scale_x_continuous(limits = c(-0.02, 0.12), 
                     breaks = seq(from = -0.02, to = 0.12, by = 0.02), 
                     expand = c(0.005, 0.005)) +
  labs(x = expression("MIT   ∆ PO"["15-min"]*"  ( W ∙ kg"^-1*") "), 
       y = expression("HIT   ∆ PO"["15-min"]*"  ( W ∙ kg"^-1*") ")) +
  theme(text=element_text(family="serif", face="plain", size=lable.size),
        legend.position = "none",
        axis.line.x = element_line(size = axis.width),
        axis.line.y = element_line(size = axis.width),
        axis.ticks = element_line(size = axis.ticks.width),
        axis.ticks.length = unit(0.05, "cm"))
figure4



# Width of figure = 2x columns 17 cm
# height of figure = 3/4 page = 23 * 0.75 cm

saveRDS(figure4, "./figures/rds/figure4.RDS")

ggsave("figures/figure4.pdf", plot = figure4, width = 8.5, height = 7, 
       dpi = 600,
       units = "cm", device= "pdf")




```


